# Generated by Django 5.1.3 on 2025-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
