# Generated by Django 5.1.3 on 2025-01-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uff', '0004_jobpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPost',
            new_name='Job',
        ),
    ]
