# Generated by Django 5.1.3 on 2025-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uff', '0005_rename_jobpost_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='app_uff.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
    ]
