# Generated by Django 5.1.3 on 2025-01-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uff', '0008_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
