# Generated by Django 5.1.3 on 2025-01-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uff', '0009_remove_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uff.freelancerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_uff.job')),
            ],
            options={
                'unique_together': {('freelancer', 'job')},
            },
        ),
    ]
